package com.fjd.dni.DataBase;

public class Tables {
   static final String PERSONAS ="CREATE TABLE PERSONAS(ID	INTEGER PRIMARY KEY AUTOINCREMENT, NOMBRES TEXT NOT NULL, APELLIDOS	TEXT NOT NULL , " +
            "CEDULA	TEXT NOT NULL,EDAD TEXT NOT NULL, SEXO TEXT NOT NULL, FECHA_NAC TEXT NOT NULL, FECHA_EXP TEXT NOT NULL, LUGAR_NAC TEXT NOT NULL," +
            "TELEFONO	INTEGER NOT NULL , EMAIL TEXT NOT NULL DEFAULT 'null', USER	TEXT DEFAULT 'null', CORREG TEXT NOT NULL, BARRIO TEXT NOT NULL, " +
            "LATITUD TEXT   DEFAULT '0.0',LONGITUD	TEXT  DEFAULT '0.0',FECHA_EJE DATE DEFAULT CURRENT_DATE , HORA_EJE TIME DEFAULT CURRENT_TIME, ESTADO TEXT DEFAULT 'N')";
   static  final String FOTOS = "CREATE TABLE FOTOS( ID INTEGER PRIMARY KEY AUTOINCREMENT,ID_FOTO varchar(100), N_FOTOS varchar(100)," +
           " ANO varchar(100), MES varchar(100), " +
            "FOTO varchar(5000),ESTADO varchar(5) DEFAULT 'P', FECHA DATE DEFAULT CURRENT_DATE)";
   static final  String BARRIOS =  "CREATE TABLE BARRIOS(DPTO TEXT NOT NULL, MPIO TEXT NOT NULL, CORREG TEXT NOT NULL," +
           " CODIGO TEXT NOT NULL, NOMBRE TEXT NOT NULL)";

   static final  String CORREG = "CREATE TABLE CORREGIMIENTOS(DPTO TEXT NOT NULL, MPIO TEXT NOT NULL, CODIGO TEXT NOT NULL, NOMBRE TEXT NOT NULL)";

   static final  String ZONA = "CREATE TABLE ZONA(DPTO TEXT NOT NULL, MPIO TEXT NOT NULL, D_DPTO TEXT NOT NULL, D_MPIO TEXT NOT NULL)";
}
